version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"

  - package-ecosystem: pip
    directory: flexget
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"

  - package-ecosystem: docker
    directory: flexget
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"

  - package-ecosystem: docker
    directory: transmission
    schedule:
      interval: weekly
      day: saturday
      time: "08:00"
      timezone: "Europe/London"
