services:
  flexget:
    build: flexget/
    restart: always
    environment:
      TZ: Europe/London
    volumes:
      - flexget_config:/flexget/config

  transmission:
    build:
      context: transmission/
      target: $TRANSMISSION_TARGET
      args:
        - FILEBOT_LICENSE=${FILEBOT_LICENSE}
    restart: always
    environment:
      EMAIL: ${FILEBOT_EMAIL}
      TZ: Europe/London
      CONFIG_OUTPUT: $CONFIG_OUTPUT
    ports:
      - '${REMOTE_PORT}:${REMOTE_PORT}'
      - '${REMOTE_PORT}:${REMOTE_PORT}/udp'
      - '${LOCAL_PORT}:${LOCAL_PORT}'
    volumes:
      - transmission_config:/transmission/config
      - /mnt/media:/media

volumes:
  flexget_config:
  transmission_config:
