name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: deployment
  cancel-in-progress: true

jobs:
  deploy-general:
    name: Deploy general instance to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickselby-web-server/actions/server-certificate@main
        with:
          CA: ${{ secrets.HOME_CA }}
          CLIENT_CERT: ${{ secrets.HOME_CLIENT_CERT }}
          CLIENT_KEY: ${{ secrets.HOME_CLIENT_KEY }}
      - uses: rickselby-web-server/actions/docker-compose-deploy@main
        with:
          STACK_NAME: transmission-general
        env:
          DOCKER_HOST: ${{ secrets.HOME_HOST }}
          DOCKER_TLS_VERIFY: 1
          FILEBOT_EMAIL: ${{ secrets.FILEBOT_EMAIL }}
          FILEBOT_LICENSE: ${{ secrets.FILEBOT_LICENSE }}
          REMOTE_PORT: 51413
          LOCAL_PORT: 9091
          TRANSMISSION_TARGET: filebot
          CONFIG_OUTPUT: /media/plex

  deploy-racing:
    name: Deploy racing instance to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickselby-web-server/actions/server-certificate@main
        with:
          CA: ${{ secrets.HOME_CA }}
          CLIENT_CERT: ${{ secrets.HOME_CLIENT_CERT }}
          CLIENT_KEY: ${{ secrets.HOME_CLIENT_KEY }}
      - uses: rickselby-web-server/actions/docker-compose-deploy@main
        with:
          STACK_NAME: transmission-racing
        env:
          DOCKER_HOST: ${{ secrets.HOME_HOST }}
          DOCKER_TLS_VERIFY: 1
          FILEBOT_EMAIL: email
          FILEBOT_LICENSE: license
          REMOTE_PORT: 51415
          LOCAL_PORT: 9093
          TRANSMISSION_TARGET: transmission
          CONFIG_OUTPUT: /media/plex

  deploy-seeding:
    name: Deploy seeding instance to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickselby-web-server/actions/server-certificate@main
        with:
          CA: ${{ secrets.HOME_CA }}
          CLIENT_CERT: ${{ secrets.HOME_CLIENT_CERT }}
          CLIENT_KEY: ${{ secrets.HOME_CLIENT_KEY }}
      - uses: rickselby-web-server/actions/docker-compose-deploy@main
        with:
          STACK_NAME: transmission-seeding
          COMPOSE_FILE_PATH: docker-compose.no-flexget.yml
        env:
          DOCKER_HOST: ${{ secrets.HOME_HOST }}
          DOCKER_TLS_VERIFY: 1
          FILEBOT_EMAIL: ${{ secrets.FILEBOT_EMAIL }}
          FILEBOT_LICENSE: ${{ secrets.FILEBOT_LICENSE }}
          REMOTE_PORT: 51416
          LOCAL_PORT: 9094
          TRANSMISSION_TARGET: filebot
          CONFIG_OUTPUT: /media/plex

  deploy-rick:
    name: Deploy Rick's instance to remote server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: rickselby-web-server/actions/server-certificate@main
        with:
          CA: ${{ secrets.HOME_CA }}
          CLIENT_CERT: ${{ secrets.HOME_CLIENT_CERT }}
          CLIENT_KEY: ${{ secrets.HOME_CLIENT_KEY }}
      - uses: rickselby-web-server/actions/docker-compose-deploy@main
        with:
          STACK_NAME: transmission-rick
        env:
          DOCKER_HOST: ${{ secrets.HOME_HOST }}
          DOCKER_TLS_VERIFY: 1
          FILEBOT_EMAIL: ${{ secrets.FILEBOT_EMAIL }}
          FILEBOT_LICENSE: ${{ secrets.FILEBOT_LICENSE }}
          REMOTE_PORT: 51417
          LOCAL_PORT: 9095
          TRANSMISSION_TARGET: filebot
          CONFIG_OUTPUT: /media/plex/Rick
